name: extension_utilities
description: A library of extension utilities on existing dart core
version: 1.0.2
repository: https://github.com/RaghavTheGreat1/extension_utilities.git

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
